AWSTemplateFormatVersion: 2020-06-20
Description: Working with nested stacks

Resources: 

  VPC:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://cfplay.s3.amazonaws.com/vpc.yaml
      TimeoutInMinutes: 5

  EC2:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://cfplay.s3.amazonaws.com/ec2.yaml
      TimeoutInMinutes: 5
    DependsOn: VPC

  RDS:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://cfplay.s3.amazonaws.com/rds.yaml
      TimeoutInMinutes: 5
    DependsOn: EC2
